apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: client-gateway
  name: client-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: client-gateway
    spec:
      containers:
      - image: europe-west9-docker.pkg.dev/microservices-shop-nestjs/image-registry/client-gateway-prod
        name: client-gateway-prod
        resources: {}
status: {}
